### PR TITLE
New station

### PR DESCRIPTION
**Pull request by BenSFGamer**
Created a new station for JSRF live to be added/implemented.

### CODE REVIEW

**Review by Mcdonoughd — COMMENTED** [review]
This is awesome,  is there a way to send the track files for the new station?

**Comment by BenSFGamer** [comment]
That did I that when working from the local Github app on my PC. I'll give
check.

**Comment by BenSFGamer** [comment]
Thought did I that when working from the local Github app on my PC. I'll
give check.

**Comment by BenSFGamer** [comment]
Still no luck on my end. I've posted a link with the track files above this post. Maybe you can implement them in the station. 

As for the other stations, how are able to add tracks (as dvc)?

**Comment by Mcdonoughd** [comment]
[radio/stations/ggs/Myammee - Birthday Suit.mp3](https://github.com/RudiesGarage/jetsetradiofuture.live/pull/4/files#diff-f2f8f6e060e39bee2f73728570549319d496139403d2af5078f225d1db00abd1) was the only mp3 added.

[DVC](https://dvc.org/) files are not a music format. They were a way to keep track of what was on the s3 bucket but they have since been removed from the repository.

I'll download the mp3s you provided and merge this when everything is finished.

**Comment by BenSFGamer** [comment]
Thanks.

**Comment by Mcdonoughd** [comment]
Thank you for contributing

**Pull request merged**
